# Workflow Code: AngryGoose_v6    DO NOT REMOVE

# Note: This workflow should not be used with CI workflows that create their own releases, this workflow would conflict with that.

name: Increment Version on Merge
on:
  pull_request:
    types: [closed]

jobs:
  increment-version:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main' # TODO:  verify default branch name

    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # See https://github.com/im-open/git-version-lite for more details around how to increment major/minor/patch through commit messages
      - name: Increment the version
        uses: im-open/git-version-lite@v2.0.6
        with:
          create-ref: true
          github-token: ${{ secrets.GITHUB_TOKEN }} # Special per-job token generated by GH for interacting with the repo
          default-release-type: major
