# Workflow Code: DeterminedPorcupine_v6    DO NOT REMOVE

name: Automatically run tf plan and comment on PR
on:
  pull_request:
    types: [opened, reopened, synchronize]
    # TODO:  Verify the paths where changes should trigger this workflow.  This can be removed entirely if all changes should trigger the workflow.
    paths:
      - 'common/**'
      - 'dev/**'
      - 'qa/**'
      - 'stage/**'
      - 'prod/**'

jobs:
  auto-plan-the-tf:
    runs-on: [self-hosted, ubuntu-20.04]

    strategy:
      matrix:
        # TODO: By default this only runs a plan against dev, but other envs can be added:  qa, stage, demo, uat, prod
        environment: [dev]

    environment: ${{ matrix.environment }}

    env:
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_ENVIRONMENT: 'public'
      TF_IN_AUTOMATION: 'true'
      TF_VERSION: '~>1.0.5' #TODO:  Verify your version of terraform.
      TF_WORKING_DIR: './${{ matrix.environment }}' # TODO:  Verify this directory structure would be correct for your repository
      SSH_KEY_CENTRAL_LOGGING: ${{ secrets.SSH_CENTRAL_LOGGING }} # This is an org level secret
      SSH_KEY_STORAGE_ACCOUNT: ${{ secrets.SSH_STORAGE_ACCOUNT }} # This is an org level secret
      SSH_KEY_NETWORK_INFO: ${{ secrets.SSH_NETWORK_INFO }} # This is an org level secret
      # TODO: If the terraform is still using on-prem-egress-ips, it needs to be switched to network-information.
      SSH_DEPLOY_KEY_INFO: |
        [
          { "orgAndRepo": "im-platform/central-logging", "envName" : "SSH_KEY_CENTRAL_LOGGING" },
          { "orgAndRepo": "im-platform/storage-account-network-rules", "envName" : "SSH_KEY_STORAGE_ACCOUNT" },
          { "orgAndRepo": "im-platform/network-information", "envName" : "SSH_KEY_NETWORK_INFO" }
        ]

    defaults:
      run:
        shell: bash
        working-directory: '${{ env.TF_WORKING_DIR }}'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: '${{ env.TF_VERSION }}'

      # Allows pulling modules from the repo instead of artifactory
      - name: Setup SSH Keys and known_hosts
        uses: im-open/setup-deploy-keys@1.0.1
        with:
          deploy-key-info: ${{ env.SSH_DEPLOY_KEY_INFO }}

      - name: Terraform Init
        id: init
        run: terraform init
        continue-on-error: true

      - name: Terraform Format
        working-directory: .
        id: fmt
        run: terraform fmt -check -recursive
        continue-on-error: true

      # TODO:  Remove the pagerduty token if not configuring pagerduty.  If using pagerduty verify 'pagerduty_token' is the name of the variable that tf expects
      # TODO:  Add any other secrets that would be required for a tf plan to succeed.  Since this is a multi-line command every line except the last will need a \ on the end of it
      # PAGERDUTY_API_KEY is an org level secret
      - name: Terraform Plan
        id: plan
        run: |
          terraform plan -no-color -lock=false \
            -var="pagerduty_token=${{ secrets.PAGERDUTY_API_KEY }}"
        continue-on-error: true

      - name: 'Terraform Comment'
        uses: actions/github-script@v4
        env:
          PLAN: "\n```\n${{ steps.plan.outputs.stdout }}\n```\n"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `### Format, Init and Plan Results for ${{ matrix.environment }} 
            #### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`
            <details><summary>Show Plan</summary>
            ${process.env.PLAN}
            </details>
            __Pusher__: @${{ github.actor }}
            __Action__: \`${{ github.event_name }}\``;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Plan Status
        if: steps.fmt.outcome == 'failure' || steps.init.outcome == 'failure' || steps.plan.outcome == 'failure'
        run: |
          echo "fmt outcome ${{ steps.fmt.outcome }}"
          echo "init outcome ${{ steps.init.outcome }}"
          echo "plan outcome ${{ steps.plan.outcome }}"
          exit 1
