name: Apply terraform to Stage/Prod
on:
  workflow_dispatch:
    inputs:
      tag:
        description: Tag for the tf that should be deployed to the Prod subscription.  It must be reachable from the default branch.
        required: true
      environment:
        description: The environment to Deploy To.
        required: true

# TODO:  The terraform needs to be switched from on-prem-egress-ips to network-information.

env:
  PLAN_STORAGE_CONTAINER: 'tfstate'
  ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
  ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
  ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
  ARM_ENVIRONMENT: 'public'
  TF_IN_AUTOMATION: 'true'
  TF_VERSION: '~>1.0.5' #TODO:  Verify your version of terraform.
  SSH_KEY_CENTRAL_LOGGING: ${{ secrets.SSH_CENTRAL_LOGGING }} # This is an org level secret
  SSH_KEY_STORAGE_ACCOUNT: ${{ secrets.SSH_STORAGE_ACCOUNT }} # This is an org level secret
  SSH_KEY_NETWORK_INFO: ${{ secrets.SSH_NETWORK_INFO }} # This is an org level secret
  SSH_KEY_ON_PREM_EGRESS: ${{ secrets.SSH_ON_PREM_EGRESS }} # This is an org level secret

jobs:
  # TODO:  Remove if you do not need stakeholder approve before deploy infrastructure to production subscription
  stakeholder-approval:
    runs-on: ubuntu-18.04 # Force this to run on github-hosted runner
    environment: 'Stakeholder Approval'
    steps:
      - name: Approval Received
        run: echo "Stakeholder approval was received"

  validate-input:
    needs: stakeholder-approval
    runs-on: ubuntu-18.04 # Force this to run on github-hosted runner
    outputs:
      env: ${{ steps.clean-env.outputs.mapped_input }}
    steps:
      # TODO:  Update for the environments you use in the Prod subscription
      - name: Clean Environment Input
        id: clean-env
        uses: im-open/map-input-action@v1.0.1
        with:
          input: ${{ github.event.inputs.environment }}
          input_map: '{ "stage": ["stg", "s", "stage"], "prod": ["prod", "production", "p"] }' # TODO: Make sure the outputted value matches the case/name of your environment tf-folder
          error_on_no_match: true
          custom_error_message: 'The environment must be Stage or Prod'

      # In this job, always checkout the default branch and get all history/tags with
      # the fetch-depth so we can check if a tag is reachable from the default branch
      # This ensures only code that has been reviewed and merged into master is deployed to Prod.
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: 'main' # TODO:  Verify this is the default branch for the repository
          fetch-depth: 0

      - uses: im-open/is-tag-reachable-from-default-branch@v1.0.0
        with:
          tag: ${{ github.event.inputs.tag }}

  tf-plan:
    needs: validate-input
    runs-on: [self-hosted, ubuntu-20.04]
    environment: ${{ needs.validate-input.outputs.env }}
    env:
      PAGERDUTY_SERVICE_IDS: '[ "${{ secrets.PAGERDUTY_SERVICE_ID }}" ]' # TODO:  Add your PD Service IDs here, the svc id usually has a format of P0XXXXX
      PAGERDUTY_WINDOW_DESC: 'Deploying Infrastructure to the ${{ needs.validate-input.outputs.env }} environment from GitHub Actions' # TODO:  Verify this description
      PAGERDUTY_WINDOW_IN_MIN: 30 # TODO:  Verify the length of your PD Maintenance Window

    defaults:
      run:
        shell: bash
        working-directory: './${{ needs.validate-input.outputs.env }}' # TODO:  Verify this directory is correct for your project

    outputs:
      tf_plan_name: ${{ steps.upload.outputs.tf_plan_name }}
      maintenance_window_id: ${{ steps.open-window.outputs.maintenance-window-id }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      # Allows pulling modules from the repo instead of artifactory
      - name: Setup SSH Keys and known_hosts
        uses: im-open/setup-deploy-keys@1.0.1
        with:
          deploy-key-info: |
            [
              { "orgAndRepo": "im-platform/central-logging", "envName" : "SSH_KEY_CENTRAL_LOGGING" },
              { "orgAndRepo": "im-platform/storage-account-network-rules", "envName" : "SSH_KEY_STORAGE_ACCOUNT" },
              { "orgAndRepo": "im-platform/network-information", "envName" : "SSH_KEY_NETWORK_INFO" },
              { "orgAndRepo": "im-platform/on-prem-egress-ips", "envName" : "SSH_KEY_ON_PREM_EGRESS" }
            ]

      - name: Open a PagerDuty Maintenance Window
        id: open-window
        uses: im-open/open-pagerduty-maintenance-window@v1.0.0
        with:
          pagerduty-api-key: ${{ secrets.PAGERDUTY_API_KEY }} # This is an org level secret
          description: '${{ env.PAGERDUTY_WINDOW_DESC }}'
          minutes: ${{ env.PAGERDUTY_WINDOW_IN_MIN }}
          service-ids: ${{ env.PAGERDUTY_SERVICE_IDS }}

      # Setting the Resource Group and Storage account so the plan can be uploaded to azure storage
      # TODO:  Set the resource group values for each environment supported in the prod subscription.  Delete any environments you aren't using.
      # If prod is the only value used here, a single global environment variable can be set for the workflow and this action can be deleted.
      - name: Set the Resource Group
        uses: im-open/set-variable-based-on-environment@v1.0.0
        with:
          variable-name: 'RESOURCE_GROUP'
          current-environment: ${{ needs.validate-input.outputs.env }}
          stage-value: ''
          prod-value: ''

      # TODO:  Set the storage account name for each environment supported in the prod subscription.  Delete any environments you aren't using.
      # If prod is the only value used here, a single global environment variable can be set for the workflow and this action can be deleted.
      - name: Set the Storage Account
        uses: im-open/set-variable-based-on-environment@v1.0.0
        with:
          variable-name: 'STORAGE_ACCOUNT'
          current-environment: ${{ needs.validate-input.outputs.env }}
          stage-value: ''
          prod-value: ''

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: '${{ env.TF_VERSION }}'

      - name: Terraform Init
        id: init
        run: terraform init

      # TODO:  Remove the pagerduty token if not configuring pagerduty.  If using pagerduty verify 'pagerduty_token' is the name of the variable that tf expects
      # PAGERDUTY_API_KEY is an organization-level secret
      # This will run a plan and output it to a file.  The file is then uploaded to azure storage so it can be used later in the apply.
      - name: Terraform Plan
        id: plan
        run: |
          mkdir plans
          terraform plan -no-color \
            -var="pagerduty_token=${{ secrets.PAGERDUTY_API_KEY }}" \
            -out=./plans/tfplan

      - name: Upload plan to blob storage
        id: upload
        shell: pwsh
        run: |
          $currentTime = Get-Date -Format "yyyymmdd-HHmmss"
          $terraformPlanName = "$(Get-Date -Format 'yyyymmdd-HHmmss').plan.zip"
          $terraformBlobName = "plans/$terraformPlanName"

          Add-Type -Assembly "System.IO.Compression.FileSystem"
          [System.IO.Compression.ZipFile]::CreateFromDirectory("plans", $terraformPlanName)

          echo "Terraform Plan Name: $terraformPlanName"
          echo "current directory:"
          ls -R

          echo "Uploading tf plan to azure storage account ${{ env.STORAGE_ACCOUNT }}"
          $key = az storage account keys list --account-name ${{ env.STORAGE_ACCOUNT }} --resource-group ${{ env.RESOURCE_GROUP }} --query [0].value -o tsv
          az storage blob upload --no-progress --auth-mode key --account-key $key --account-name ${{ env.STORAGE_ACCOUNT }} --container-name ${{ env.PLAN_STORAGE_CONTAINER }} --file $terraformPlanName --name $terraformBlobName
          echo "The plan was successfully uploaded"

          echo "::set-output name=tf_plan_name::$terraformPlanName"

      - name: Azure logout
        run: |
          az logout
          az cache purge
          az account clear

  tf-plan-manual-approval:
    needs: tf-plan
    runs-on: ubuntu-18.04 # Force this to run on github-hosted runner
    environment: 'Technical Approval'
    steps:
      - name: Approval Received
        run: |
          echo "Approval on the tf plan was received"

  tf-apply:
    needs: [tf-plan-manual-approval, tf-plan]
    runs-on: [self-hosted, ubuntu-20.04]
    environment: ${{ needs.validate-input.outputs.env }}

    defaults:
      run:
        shell: bash
        working-directory: './${{ needs.validate-input.outputs.env }}' # TODO:  Verify this directory is correct for your project

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.tag }}

      # Allows pulling modules from the repo instead of artifactory
      - name: Setup SSH Keys and known_hosts
        uses: im-open/setup-deploy-keys@1.0.1
        with:
          deploy-key-info: |
            [
              { "orgAndRepo": "im-platform/central-logging", "envName" : "SSH_KEY_CENTRAL_LOGGING" },
              { "orgAndRepo": "im-platform/storage-account-network-rules", "envName" : "SSH_KEY_STORAGE_ACCOUNT" },
              { "orgAndRepo": "im-platform/network-information", "envName" : "SSH_KEY_NETWORK_INFO" },
              { "orgAndRepo": "im-platform/on-prem-egress-ips", "envName" : "SSH_KEY_ON_PREM_EGRESS" }
            ]

      # Setting the Resource Group and Storage account so the plan can be downloaded from azure storage
      # TODO:  Set the resource group values for each environment supported in the prod subscription.  Delete any environments you aren't using.
      # If prod is the only value used here, a single global environment variable can be set for the workflow and this action can be deleted.
      - name: Set the Resource Group
        uses: im-open/set-variable-based-on-environment@v1.0.0
        with:
          variable-name: 'RESOURCE_GROUP'
          current-environment: ${{ needs.validate-input.outputs.env }}
          stage-value: ''
          prod-value: ''

      # TODO:  Set the storage account name for each environment supported in the prod subscription.  Delete any environments you aren't using.
      # If prod is the only value used here, a single global environment variable can be set for the workflow and this action can be deleted.
      - name: Set the Storage Account
        uses: im-open/set-variable-based-on-environment@v1.0.0
        with:
          variable-name: 'STORAGE_ACCOUNT'
          current-environment: ${{ needs.validate-input.outputs.env }}
          stage-value: ''
          prod-value: ''

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup Terraform
        id: setup
        uses: hashicorp/setup-terraform@v1.2.1
        with:
          terraform_version: '${{ env.TF_VERSION }}'

      - name: Download blob
        shell: pwsh
        run: |
          mkdir plans
          echo "Current working directory: $pwd"
          $terraformBlobName = "plans/${{ needs.tf-plan.outputs.tf_plan_name }}"
          echo "The blob name is: $terraformBlobName"

          Write-Host "Download blob to ./plans"
          $key = az storage account keys list --account-name ${{ env.STORAGE_ACCOUNT }} --resource-group ${{ env.RESOURCE_GROUP }} --query [0].value -o tsv
          az storage blob download --no-progress --auth-mode key --account-key $key --account-name ${{ env.STORAGE_ACCOUNT }} --container-name ${{ env.PLAN_STORAGE_CONTAINER }} --file $pwd/$terraformBlobName --name $terraformBlobName

          try {
            [System.IO.Compression.ZipFile]::ExtractToDirectory("$pwd/$terraformBlobName", "$pwd/plans")    
          }
          catch {
            # Even though it hits this catch block the archive is extracted as expected.  No good explanation.
          }

          Write-Host "Zip extracted"

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve -no-color -input=false ./plans/tfplan

      - name: Azure logout
        run: |
          az logout
          az cache purge
          az account clear

      - name: Close the PagerDuty Maintenance Window
        uses: im-open/close-pagerduty-maintenance-window@v1.0.0
        with:
          pagerduty-api-key: ${{ secrets.PAGERDUTY_API_KEY }} # This is an org level secret
          maintenance-window-id: ${{ needs.tf-plan.outputs.maintenance_window_id }}

  # TODO: Remove if not using an automated deployment project board
  # https://github.com/im-practices/git-er-done/blob/main/actions/deployment-board.md
  update-deployment-board:
    runs-on: ubuntu-18.04 # Force this to run on github-hosted runner
    needs:
      [
        stakeholder-approval,
        validate-input,
        tf-plan,
        tf-plan-manual-approval,
        tf-apply,
      ]
    if: always()
    steps:
      - uses: im-open/workflow-conclusion@v1.0.1
        id: conclusion
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Deployment Board
        if: always()
        uses: im-open/update-deployment-board@v1.0.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          environment: ${{ needs.validate-input.outputs.env }}
          board-number: '' # TODO: Add the automated deployment board number or remove if not using an automated deployment project board.
          ref: ${{ github.event.inputs.tag }}
          deploy-status: ${{ steps.conclusion.outputs.workflow_conclusion }}
          timezone: 'america/denver'
