# Workflow Code: CockySquirrel_v1    DO NOT REMOVE

name: Runbook - Add or update azure keyvault secret
# TODO:  You may wish to add the name of the key vault to the name above and the file name if there are multiple key vaults this repository can add secrets to

on:
  workflow_dispatch:
    inputs:
      secret_name:
        description: The name of the secret to add, azure requires it conform to the following pattern - ^[0-9a-zA-Z-]+$
        required: true
      secret_value:
        description: The value of the secret
        required: true
      environment:
        description: The environment to add the secret to - dev|qa|stage|prod|demo|uat
        required: true
        default: prod

jobs:
  set-vars:
    runs-on: ubuntu-latest # Force this to run on github-hosted runner by using a tag that does not exist on self-hosted runners

    # To use any of these outputs in another job use the following syntax: ${{ needs.set-vars.outputs.ENVIRONMENT }}
    outputs:
      ENVIRONMENT: ${{ steps.clean-env.outputs.mapped_input }}
      RESOURCE_GROUP: ${{ steps.rgrp.outputs.RESOURCE_GROUP }}
      KEYVAULT_NAME: ${{ steps.stg-acct.outputs.KEYVAULT_NAME }}

    steps:
      # To use this value: ${{ needs.set-vars.outputs.ENVIRONMENT }}
      - name: Set ENVIRONMENT
        id: clean-env
        uses: im-open/map-input-action@v1.0.1
        with:
          input: ${{ github.event.inputs.environment }}
          # TODO:  Update for the environments your project contains
          # The value array contains the environments it will match and the corresponding key is
          # the environment it will output if one of the values was found.  It is case insensitive.
          input_map: |
            { 
              "dev": ["dev", "d", "development"], 
              "qa": ["qa", "q"], 
              "stage": ["stg", "s", "stage"], 
              "demo": ["o", "demo"], 
              "uat": ["u", "uat"], 
              "prod": ["prod", "production", "p"] 
            }
          error_on_no_match: true
          custom_error_message: 'The environment must be Dev, QA, Stage Demo, UAT or Prod'

      - run: echo "The current environment is ${{ steps.clean-env.outputs.mapped_input }}"

      - uses: im-open/set-variable-based-on-environment@v1.0.0
        with:
          variable-name: 'KEYVAULT_NAME'
          current-environment: ${{ steps.clean-env.outputs.mapped_input }}
          # TODO: For the following keyvault name inputs, fill in the value if you have the environment and delete the environment if it does not exist
          dev-value: ''
          qa-value: ''
          stage-value: ''
          demo-value: ''
          uat-value: ''
          prod-value: ''

  set-secret:
    runs-on: [self-hosted, ubuntu-20.04]

    environment: ${{ needs.set-vars.outputs.ENVIRONMENT }}

    steps:
      - run: echo "The current environment is ${{ needs.set-vars.outputs.ENVIRONMENT }}"

      - name: Mask the secret value
        uses: actions/github-script@v4
        with:
          script: |
            core.info(`Masking the value for ${context.payload.inputs.secret_name} so it is not exposed.`);
            core.setSecret(context.payload.inputs.secret_value);

      - name: AZ Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }} # TODO: Ensure this secret has been populated in your repo

      - name: keyvault set
        run: az keyvault secret set --name ${{ github.event.inputs.secret_name }} --vault-name ${{ needs.set-vars.outputs.KEYVAULT_NAME }} --subscription ${{ secrets.ARM_SUBSCRIPTION_ID }} --value "${{ github.event.inputs.secret_value }}"

      - name: Azure logout
        if: always() && steps.login.outcome == 'success'
        run: |
          az logout
          az cache purge
          az account clear
