# Workflow Code: ZestyFlamingo_v8    DO NOT REMOVE
# Purpose: 
#    Uses a container to run a K6 stress test against the environment and 
#    with the test file the user specifies when they kick it off manually.
#
# Frequency:
#    - This workflow is intended to be reusable, and used once per repository.
#      If the workflow is updated to hardcode some arguments like test-file 
#      and test-root-folder instead of taking them in as args, then it could 
#      be duplicated, once per k6 project in the repo.
#    
# Projects to use this Template with:
#    - App Service or Function (Optional Template)
#    - On-Prem Service         (Optional Template)

name: Manual trigger K6 test

on:
  workflow_dispatch:
    inputs:
      env-to-test:
        description: 'Environment to run test against'
        required: true
        default: 'dev'
        type: choice
        options: # TODO:  Update for the environments your k6 test can be run against
          - dev
          - qa
          - stage
      test-folder-root:
        description: 'Root directory of k6 test files including configs, etc. IE: tests/k6'
        required: true
        default: '' # TODO: Add the location of your tests.  IE: tests/k6
      test-file:
        description: 'K6 test file to run'
        required: true
        default: '' # TODO: Add default test file  IE: check-health-simple.js
      k6-extra-params:
        description: 'K6 command extra paramaters'
        required: false
        default: '' # TODO: Set default paramaters to run on every K6 test. IE. --vus 1 -i 1 --insecure-skip-tls-verify -out JSON="./k6-output.json" --out influxdb="http://influxdb:8086/k6" --config "/scripts/config/dev-config.json"
      k6-version:
        description: 'K6 version.  Versions lower than 0.32.0 will not work with this action.  Do not include the "v" prefix.'
        required: true
        default: '' # TODO: Set default version of k6. IE. 0.33.0
      run-stress-step:
        description: 'Run k6 stress test optimized step. The optimized step allows more connections and transactions.'
        required: false
        default: 'false'
        type: boolean

jobs:
  k6_test:
    runs-on: [self-hosted, ubuntu-20.04]
    steps:
      - run: echo "The current environment is ${{ github.event.inputs.env-to-test }}"

      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup K6
        uses: im-open/setup-k6-perf-testing@v1.0.1
        with:
          version: ${{ github.event.inputs.k6-version }}

      - name: Validate test file exists
        run: |
          echo "Checking if test file exists:"
          FILE="./${{ github.event.inputs.test-folder-root }}/${{ github.event.inputs.test-file }}"
          if [[ -f $FILE ]]; then
            echo "$FILE exists."
          else
            echo "Could not find test file. $FILE"
            exit 1
          fi

      # Depending on the flag set above one of these run k6 steps will execute.  The difference between these two
      # steps is the number of open connections it configures.  The stress step allows more connections on the OS.
      - name: Run local k6 test
        if: ${{ github.event.inputs.run-stress-step != 'true' }}
        working-directory: ${{ github.event.inputs.test-folder-root }}
        run: |
          k6 run ${{ github.event.inputs.test-file }} ${{ github.event.inputs.k6-extra-params }} -e RUN_ENV=${{ github.event.inputs.env-to-test }}

      - name: Run local k6 as a stress test
        if: ${{ github.event.inputs.run-stress-step == 'true' }}
        working-directory: ${{ github.event.inputs.test-folder-root }}
        run: |
          # ulimit must be set in k6 step as it gets reset every session.
          # The nofile limit cannot exceed the hard limit.  You will get a permission denied if you do.
          ulimit -n 1048576
          echo "Open Files, Reuse TCP ports, and Port Range below:"
          ulimit -Sa | grep 'open files'
          sudo sysctl -a | grep -E 'net.ipv4.ip_local_port_range|net.ipv4.tcp_tw_reuse|fs.file-max'
          k6 run ${{ github.event.inputs.test-file }} ${{ github.event.inputs.k6-extra-params }} -e RUN_ENV=${{ github.event.inputs.env-to-test }}
